# Generated by Django 3.0.1 on 2019-12-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='who',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
